[package]
name = "rebalance-app"
version = "0.1.0"
authors = ["Alberto Leal <mailforalberto@gmail.com>"]

[dependencies]
csv = "1.0.5"
tabwriter = "1.1.0"

[dependencies.num]
git = "https://github.com/rust-num/num"
rev = "ef752e46877dc163ec28ddcf4d71558c264bb78d"
